### ISSUE TITLE
Minecraft Color Codes coming back with responce 

### ISSUE THREAD

**Issue by jerlegoman** [bipio-server/bip-pod-minecraft#1]
Hi its me Jeremy. There is an issue with the Minecraft pod. When I set a bip up to send me server info, I get the name of the server but with the color codes (the codes that add color to the server info in-game this is it "Â§bÂ§lÂ§m Â§8Â§lÂ§m[ Â§r Â§9Â§lMineplexÂ§r Â§fÂ§lGamesÂ§r Â§8Â§lÂ§m ]Â§bÂ§lÂ§m Â§r")
for more info about minecraft color codes go here: http://minecraftonline.com/wiki/Colour_codes

**Comment by mjpearson** [comment]
Thanks Jeremy!  I just pushed a fix and this is available also on the bip.io site
